### ISSUE TITLE
Implement pebble watch notifications from app

### ISSUE THREAD

**Issue by hklebs** [justbeneu/JustBe-Android#15]
for momentary evaluations

**Comment by golf1052** [comment]
0f58982affa565dd159bf9d62e0d8696c782a9d1 implements a Singleton class for Pebble notifications.

All you (should) need to do is

``` java
PebbleCommunicator comms = PebbleCommunicator.getInstance();
comms.sendPebbleMessage("*MESSAGE TITLE*", "*MESSAGE BODY*");
```

To test if this actually works we need a physical Android phone that is connected to a physical Pebble.
