### ISSUE TITLE
Update account creation to only require username, password, meditation times

### ISSUE THREAD

**Issue by hklebs** [justbeneu/JustBe-Android#16]

**Comment by EdHurtig** [comment]
Requirements update: no first name or email collection in the app

**Comment by EdHurtig** [comment]
Only collect username, password, and meditation times

**Comment by hklebs** [comment]
This involves adding the tests for GettingStartedActivity as well

**Comment by ColinKohler** [comment]
https://github.com/justbeneu/JustBe-Android/pull/38

**Comment by EdHurtig** [comment]
Woo!
