### ISSUE TITLE
Add basic view transition tests

### ISSUE THREAD

**Issue by ColinKohler** [justbeneu/JustBe-Android#20]
We will need to decide on what testing software to use to simulate touches automatically on the simulator. There are a lot of options so someone should take the time to do a little research first.

**Comment by haonan92** [comment]
There is a testing software called Monkey talk, which can notice every action that users make, and making test. So I plan to start working on this tester first to see whether it can meet our test requirement

**Comment by hklebs** [comment]
There is a provided option that may be easier: http://developer.android.com/training/testing/ui-testing/espresso-testing.html

http://developer.android.com/training/testing/ui-testing/index.html

**Comment by haonan92** [comment]
![192112452442192](https://cloud.githubusercontent.com/assets/12194775/11389389/39630f12-930e-11e5-9e3c-655699144cad.png)

**Comment by haonan92** [comment]
This is the basic instruction for Configurations setup
1.Run->Edit Configurations;
2.choose the + symbol on the left corner
3. select Android Tests
4. change the Name
5. Module choose app
6.specific instrumentation runner    I choose "Junit RUnner"
7.Target Device I choose Show chooser dialog
8. then finish

**Comment by haonan92** [comment]
![192142405889811](https://cloud.githubusercontent.com/assets/12194775/11389433/b56bf966-930e-11e5-82ef-a28e71417d28.jpg)

**Comment by hklebs** [comment]
Thanks Hounan, I will take a look at this and add more tests

**Comment by hklebs** [comment]
c3aea69 & 18e71d1 & 3e0c2c2

**Comment by hklebs** [comment]
Useful testing overview:

http://www.vogella.com/tutorials/AndroidTestingEspresso/article.htmlt
