### ISSUE TITLE
Generate Models for Database objects

### ISSUE THREAD

**Issue by EdHurtig** [justbeneu/JustBe-Android#39]
We don't need every one of these but these are the tables in the database that need to be reflected
- Assessment pushs  
- Assessments  
- Exercise pushs  
- Exercise reminders  
- Exercise sessions 
- Meditation pushs  
- Meditation sessions  
- Multi select responses  
- Responses
- Users
- Groups

**Comment by ColinKohler** [comment]
This done with: https://github.com/justbeneu/JustBe-Android/pull/44?

**Comment by EdHurtig** [comment]
Not quite done yet
