### ISSUE TITLE
Finish settings screen, needs to support user setting when they wake up and go to sleep

### ISSUE THREAD

**Issue by hklebs** [justbeneu/JustBe-Android#6]
- We also need to remove last name, age, gender from the settings
- people need to set when they wake up and go to sleep
  "The user should specify when they wake up and when they go to bed before they start the program."

**Comment by hklebs** [comment]
![image](https://cloud.githubusercontent.com/assets/2482288/11232188/03a435f8-8d7e-11e5-98c1-9771b29cf871.png)

**Comment by ColinKohler** [comment]
This ticket is just for the UI right?

**Comment by ColinKohler** [comment]
I'm also adding https://github.com/code-troopers/android-betterpickers for better pickers, the defaults are pretty turrable.

**Comment by ColinKohler** [comment]
https://github.com/justbeneu/JustBe-Android/pull/21
