### ISSUE TITLE
Fully develop screens for momentary exercises

### ISSUE THREAD

**Issue by hklebs** [justbeneu/JustBe-Android#7]
We need to update this to have the better draggable bar we talked about at first meeting and figure out what exactly the different types of momentary exercises to develop the different screens for them

**Comment by hklebs** [comment]
![image](https://cloud.githubusercontent.com/assets/2482288/11232154/c244d9b4-8d7d-11e5-9721-170868ed2f0b.png)

**Comment by ColinKohler** [comment]
Added Sleep Assessment View and changed some other small stuff at https://github.com/justbeneu/JustBe-Android/pull/31. Thought about running all the assessments through one AssessmentActivity but decided against it to simply the code.

**Comment by ColinKohler** [comment]
Useful tool when creating existing android assets in different colors: http://android-holo-colors.com/

**Comment by ColinKohler** [comment]
![stess assessment](https://cloud.githubusercontent.com/assets/3207956/11454059/86ef6986-95ef-11e5-9996-75b9914d5892.PNG)

**Comment by ColinKohler** [comment]
Dunno exactly what we decided on for this slider but I think this works. https://github.com/justbeneu/JustBe-Android/pull/32

**Comment by ColinKohler** [comment]
I created the 3 assessments we know of at the moment. Closing and will open new tickets if Prof. decides she wants more or some shit.
