### ISSUE TITLE
Logic for presenting momentary exercises to users

### ISSUE THREAD

**Issue by hklebs** [justbeneu/JustBe-Android#8]
- Now momentary assessments should be 4 times a day. The user should specify when they wake up and when they go to bed before they start the program. Then assessments should happen randomly 4 times between those hours.
- Two assessments can't be closer than 30 minutes apart
- wake up and sleep times in are from user's settings, which is added from ticket

**Comment by ColinKohler** [comment]
I commented some of this out in Main cause it was crashing the app...
